AllCops:
  DisabledByDefault: false

Metrics:
  Enabled: false

Style/Encoding:
  Enabled: true

Layout/IndentationStyle:
  IndentationWidth: 2
  EnforcedStyle: spaces

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
