CHAT_CHANNEL_ROOM_PREFIX = "chat_channel_room_".freeze

# ユーザー
USER_ROLE_USER = 1
USER_ROLE_ADMIN = 2
USER_AUTHENTICATION_LOCK_COUNT = 3

# 伝票ステータス
SLIP_STATUS_UNASSIGNED = 1000
SLIP_STATUS_ASSIGNED = 2000
SLIP_STATUS_REJECT = 3000
SLIP_STATUS_ACCEPT = 4000
SLIP_STATUS_PICKUP = 5000
SLIP_STATUS_DELIVER = 6000
SLIP_STATUS_COMPLETE = 7000
