name: "Docker Hub"
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker image build . -t dennokotsu/denno_mobility:${{ github.ref_name }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: dennokotsu
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: docker image push dennokotsu/denno_mobility:${{ github.ref_name }}
